# -*- coding: utf-8 -*-
"""TicTacToe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qIRDIUf6zx3KkCVccaLCLN0qO1R7juV5
"""

#!/usr/bin/env python3
"""
Tic-Tac-Toe (Terminal, 2-Player)

Run:
  python tic_tac_toe.py
"""

from typing import List, Optional, Tuple

WIN_LINES: Tuple[Tuple[int, int, int], ...] = (
    (0, 1, 2), (3, 4, 5), (6, 7, 8),  # rows
    (0, 3, 6), (1, 4, 7), (2, 5, 8),  # cols
    (0, 4, 8), (2, 4, 6),             # diagonals
)

def print_board(board: List[str]) -> None:
    def cell(i: int) -> str:
        return board[i] if board[i] != " " else str(i + 1)

    print()
    print(f" {cell(0)} | {cell(1)} | {cell(2)} ")
    print("---+---+---")
    print(f" {cell(3)} | {cell(4)} | {cell(5)} ")
    print("---+---+---")
    print(f" {cell(6)} | {cell(7)} | {cell(8)} ")
    print()

def check_winner(board: List[str]) -> Optional[str]:
    for a, b, c in WIN_LINES:
        if board[a] != " " and board[a] == board[b] == board[c]:
            return board[a]
    return None

def is_draw(board: List[str]) -> bool:
    return all(space != " " for space in board)

def get_move(board: List[str], player: str) -> int:
    while True:
        raw = input(f"Player {player}, choose a spot (1-9): ").strip()
        if not raw.isdigit():
            print("Please enter a number from 1 to 9.")
            continue

        move = int(raw)
        if move < 1 or move > 9:
            print("That number must be between 1 and 9.")
            continue

        idx = move - 1
        if board[idx] != " ":
            print("That spot is taken. Pick another.")
            continue

        return idx

def play_game() -> None:
    board = [" "] * 9
    current = "X"

    print("Tic-Tac-Toe!")
    print("Enter 1-9 to place your mark.\n")
    print_board(board)

    while True:
        idx = get_move(board, current)
        board[idx] = current
        print_board(board)

        winner = check_winner(board)
        if winner:
            print(f"🎉 Player {winner} wins!")
            break

        if is_draw(board):
            print("🤝 It's a draw!")
            break

        current = "O" if current == "X" else "X"

def main() -> None:
    while True:
        play_game()
        again = input("Play again? (y/n): ").strip().lower()
        if again not in ("y", "yes"):
            print("Thanks for playing!")
            return

if __name__ == "__main__":
    main()

